### ISSUE TITLE
核心通識分類

### ISSUE THREAD

**Issue by ifTNT** [NUKCSIE110/coursElf#3]
思維方法
美學素養
公民素養
文化素養
科學素養
倫理素養

**Comment by kaibaooo** [comment]
@ifTNT 
課號開頭分類六向度 有要簡化DBㄇ
CCC5 科學素養
CCC6 倫理素養
CCI1 思維方法
CCI2 美學素養
CCO3 公民素養
CCO4 文化素養

**Comment by ifTNT** [comment]
哦哦 原來他有規律噢 那我就用分博雅通識的方法下去分
